### ISSUE TITLE
Examples for jetty 10 or 11

### ISSUE THREAD

**Issue by patrickhuy** [jetty-project/embedded-jetty-websocket-examples#21]
The examples presented here are for Jetty 9.x
With Jetty 10 the Websocket API changed, are there examples available for that as well?

**Comment by lachlan-roberts** [comment]
@joakime @patrickhuy I have created a branch on this repository with updated examples using Jetty version `10.0.2`.

See https://github.com/jetty-project/embedded-jetty-websocket-examples/tree/10.0.x

**Comment by patrickhuy** [comment]
Thanks! This is very helpful

**Comment by joakime** [comment]
I"ll clean this up a bit more.

* Rename branch `master` -> `jetty-9.4.x`
* Create `jetty-11.0.x` branch
* Make `jetty-10.0.x` branch the default branch
* Update the README.md for all 3 branches to point to each other's branches options.

**Comment by joakime** [comment]
Closing, as it was completed a while ago.
