### ISSUE TITLE
Migrating from jetty 9 to jetty 11

### ISSUE THREAD

**Issue by AhmedHumk** [jetty-project/embedded-jetty-websocket-examples#335]
in my jetty 9 project i was having a jetty websocket client connecting to a server with the following code 

```
connect("wss://janus.conf.meetecho.com/ws", true, "Sec-WebSocket-Protocol", "janus-protocol");

public void connect(String wsurl, Boolean addheader, String CustomHeader, String HeaderValue) {
		try {
			
			URI serveruri = new URI(wsurl);
			
			 // Start the WebSocket client in a separate thread
            Runnable connectRunnable = new Runnable() {

				@Override
				public void run() {
					try {
						request = new ClientUpgradeRequest();
						if(addheader) {
							request.setHeader(CustomHeader, HeaderValue);
						}
						
						Wsclient.start();
						
						wsEvents = new MyWSHandler();
						
						Clientsession = Wsclient.connect(wsEvents, serveruri, request);
						
					} catch (Exception e) {
						handleException("connect", e);
					}
					
				}
            	
            };
            
            Thread t = new Thread(connectRunnable);
    		t.setDaemon(true);
    		t.start();
            
		} catch (Exception e) {
			
			handleException("connect", e);
			
		}
		
	}
```

I was able to connect normally to the server with jetty 9. but when i migrated to jetty 11 i always get this error :

`org.eclipse.jetty.websocket.core.exception.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 502 Bad Gateway`

i am able to connect to the server with many other websocket clients as well . only with jetty 11 i encountered with this error

**Comment by AhmedHumk** [comment]
fixed by setting the ClientUpgradeRequest using subprotocol 

`request.setSubProtocols(HeaderValue);`

there should be a documentation for that !.

**Comment by joakime** [comment]
> fixed by setting the ClientUpgradeRequest using subprotocol
> 
> `request.setSubProtocols(HeaderValue);`
> 
> there should be a documentation for that !.

Here you go https://eclipse.dev/jetty/documentation/jetty-11/programming-guide/index.html#pg-client-websocket

BTW, Jetty 11 is now at End of Community Support.

* https://github.com/jetty/jetty.project/issues/10485
